# Generated by Django 3.1.5 on 2021-02-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210203_0943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
